### ISSUE TITLE
Questionable search engine behavior

### ISSUE THREAD

**Issue by bortzmeyer** [Meewan/MercrediFiction#5]
1) When you search by content, it also searches in the author's addresses (I searched "unix" and I got two toots unrelated to Unix, but hosted at unixcorn.xyz)

2) By default, it finds words where the search term is just a part of it (I searched "tique" and I got toots without this nasty insect, but with "plastique", "moustique", etc) At least, it should be configurable, otherwise short search terms like "mer" are completely unsearchable.

**Comment by Meewan** [comment]
1. It is because of the links in the toot. It you tage the link around #MercrediFiction you will see unix in its src. I don't know how to fix this problem without parsing the whole html each time.

2. Good idea, I will add it for next relase (but you can achieve the same behavior with adding whitespace around the word).

**Comment by bortzmeyer** [comment]
1) You *have to* parse the HTML because otherwise, there is a serious security risk (you need to keep only "safe" elements). And you need to convert it to XML for EPUB, anyway.

2) OK, it works, but it should be documented

**Comment by Meewan** [comment]
1. done

**Comment by Meewan** [comment]
2. should be done

**Comment by Meewan** [comment]
done
